# Development Environment Config

spring:
  data:
    redis:
      host: localhost
      port: 6379

aliyun:
  sms:
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    sign-name: ${ALIYUN_SMS_SIGN_NAME}
    template-code: ${ALIYUN_SMS_TEMPLATE_CODE}

cors:
  allowed-origins: "*"

logging:
  level:
    com.ciphertool: DEBUG


