function getLogicHTML() {
    return `
        <div class="container" id="logic-list-container">
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('sudoku-workspace').style.display='flex'; window.initSudokuGrid && window.initSudokuGrid();">数独</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('akari-workspace').style.display='flex'; window.initAkariGrid && window.initAkariGrid();">Akari</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('aqre-workspace').style.display='flex'; window.initAqreGrid && window.initAqreGrid();">Aqre</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('aquapelago-workspace').style.display='flex'; window.initAquapelagoGrid && window.initAquapelagoGrid();">Aquapelago</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('aquarium-workspace').style.display='flex'; window.initAquariumGrid && window.initAquariumGrid();">Aquarium</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('balanceloop-workspace').style.display='flex'; window.initBalanceloopGrid && window.initBalanceloopGrid();">Balanceloop</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('battleship-workspace').style.display='flex'; window.initBattleshipGrid && window.initBattleshipGrid();">Battleship</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('binairo-workspace').style.display='flex'; window.initBinairoGrid && window.initBinairoGrid();">Binairo</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('castlewall-workspace').style.display='flex'; window.initCastlewallGrid && window.initCastlewallGrid();">Castlewall</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('cave-workspace').style.display='flex'; window.initCaveGrid && window.initCaveGrid();">Cave</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('chocobanana-workspace').style.display='flex'; window.initChocobananaGrid && window.initChocobananaGrid();">Chocobanana</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('chocona-workspace').style.display='flex'; window.initChoconaGrid && window.initChoconaGrid();">Chocona</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('countryroad-workspace').style.display='flex'; window.initCountryroadGrid && window.initCountryroadGrid();">Countryroad</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('doppelblock-workspace').style.display='flex'; window.initDoppelblockGrid && window.initDoppelblockGrid();">Doppelblock</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('easyas-workspace').style.display='flex'; window.initEasyasGrid && window.initEasyasGrid();">Easyas</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('fillomino-workspace').style.display='flex'; window.initFillominoGrid && window.initFillominoGrid();">Fillomino</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('gokigen-workspace').style.display='flex'; window.initGokigenGrid && window.initGokigenGrid();">Gokigen</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('haisu-workspace').style.display='flex'; window.initHaisuGrid && window.initHaisuGrid();">Haisu</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('haisuslow-workspace').style.display='flex'; window.initHaisuslowGrid && window.initHaisuslowGrid();">Haisuslow</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('hamle-workspace').style.display='flex'; window.initHamleGrid && window.initHamleGrid();">Hamle</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('hashi-workspace').style.display='flex'; window.initHashiGrid && window.initHashiGrid();">Hashi</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('heteromino-workspace').style.display='flex'; window.initHeterominoGrid && window.initHeterominoGrid();">Heteromino</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('heyawake-workspace').style.display='flex'; window.initHeyawakeGrid && window.initHeyawakeGrid();">Heyawake</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('hitori-workspace').style.display='flex'; window.initHitoriGrid && window.initHitoriGrid();">Hitori</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('hotaru-workspace').style.display='flex'; window.initHotaruGrid && window.initHotaruGrid();">Hotaru Beam</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('kakuro-workspace').style.display='flex'; window.initKakuroGrid && window.initKakuroGrid();">Kakuro</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('kuromasu-workspace').style.display='flex'; window.initKuromasuGrid && window.initKuromasuGrid();">Kuromasu</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('kurotto-workspace').style.display='flex'; window.initKurottoGrid && window.initKurottoGrid();">Kurotto</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('lits-workspace').style.display='flex'; window.initLITSGrid && window.initLITSGrid();">LITS</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('magnets-workspace').style.display='flex'; window.initMagnetsGrid && window.initMagnetsGrid();">Magnets</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('masyu-workspace').style.display='flex'; window.initMasyuGrid && window.initMasyuGrid();">Masyu</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('minesweeper-workspace').style.display='flex'; window.initMSGrid && window.initMSGrid();">Minesweeper</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('moonsun-workspace').style.display='flex'; window.initMSUGrid && window.initMSUGrid();">Moonsun</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('nagare-workspace').style.display='flex'; window.initNGGrid && window.initNGGrid();">Nagare</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('nanro-workspace').style.display='flex'; window.initNRGrid && window.initNRGrid();">Nanro</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('ncells-workspace').style.display='flex'; window.initNCGrid && window.initNCGrid();">Ncells</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('nonogram-workspace').style.display='flex'; window.initNOGrid && window.initNOGrid();">Nonogram</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('norinori-workspace').style.display='flex'; window.initNRIGrid && window.initNRIGrid();">Norinori</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('numberlink-workspace').style.display='flex'; window.initNLGrid && window.initNLGrid();">Numberlink</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('nuribou-workspace').style.display='flex'; window.initNuribouGrid && window.initNuribouGrid();">Nuribou</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('nurikabe-workspace').style.display='flex'; window.initNurikabeGrid && window.initNurikabeGrid();">Nurikabe</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('nurimisaki-workspace').style.display='flex'; window.initNurimisakiGrid && window.initNurimisakiGrid();">Nurimisaki</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('onsen-workspace').style.display='flex'; window.initOnsenGrid && window.initOnsenGrid();">Onsen</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('rippleeffect-workspace').style.display='flex'; window.initRippleGrid && window.initRippleGrid();">Ripple Effect</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('shakashaka-workspace').style.display='flex'; window.initShakashakaGrid && window.initShakashakaGrid();">Shakashaka</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('shikaku-workspace').style.display='flex'; window.initShikakuGrid && window.initShikakuGrid();">Shikaku</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('shimaguni-workspace').style.display='flex'; window.initShimaguniGrid && window.initShimaguniGrid();">Shimaguni</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('skyscrapers-workspace').style.display='flex'; window.initSkyscrapersGrid && window.initSkyscrapersGrid();">Skyscrapers</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('slitherlink-workspace').style.display='flex'; window.initSlitherlinkGrid && window.initSlitherlinkGrid();">Slitherlink</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('spiralgalaxies-workspace').style.display='flex'; window.initSGGrid && window.initSGGrid();">Spiral Galaxies</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('starbattle-workspace').style.display='flex'; window.initSBGrid && window.initSBGrid();">Starbattle</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('statuepark-workspace').style.display='flex'; window.initStatueparkGrid && window.initStatueparkGrid();">Statue Park</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('stostone-workspace').style.display='flex'; window.initStostoneGrid && window.initStostoneGrid();">Stostone</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('tapa-workspace').style.display='flex'; window.initTapaGrid && window.initTapaGrid();">Tapa</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('tatamibari-workspace').style.display='flex'; window.initTatamibariGrid && window.initTatamibariGrid();">Tatamibari</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('tents-workspace').style.display='flex'; window.initTentsGrid && window.initTentsGrid();">Tents</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('tll-workspace').style.display='flex'; window.initTllGrid && window.initTllGrid();">TLL</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('tren-workspace').style.display='flex'; window.initTrenGrid && window.initTrenGrid();">Tren</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('yajilin-workspace').style.display='flex'; window.initYajilinGrid && window.initYajilinGrid();">Yajilin</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('yajisankazusan-workspace').style.display='flex'; window.initYKGrid && window.initYKGrid();">Yajisan-Kazusan</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('yinyang-workspace').style.display='flex'; window.initYinyangGrid && window.initYinyangGrid();">Yin Yang</button>
        </div>
        
        <div id="logic-workspace-container" style="display: none; padding-top: 4rem; margin-top: 2rem;">
            ${(window.logicWorkspaceHTMLs || []).join('\n')}
        </div>
    </div>`;
}

function hydrateLogicPuzzleTargets(root = document) {
    const buttons = root.querySelectorAll('.logic-btn');
    buttons.forEach(btn => {
        const onclick = btn.getAttribute('onclick') || '';
        const workspaceMatch = onclick.match(/getElementById\('([a-z0-9-]+)-workspace'\)\.style\.display='flex'/i);
        if (!workspaceMatch) return;

        const target = workspaceMatch[1];
        btn.dataset.target = target;
        btn.dataset.workspace = `${target}-workspace`;
        if (!btn.getAttribute('aria-label')) {
            btn.setAttribute('aria-label', `打开逻辑谜题 ${btn.textContent.trim() || target}`);
        }
    });
}

function initLogicModule() {
    const container = document.getElementById('luojimiti');
    if (container) {
        container.innerHTML = getLogicHTML();
        hydrateLogicPuzzleTargets(container);
    }
}
