function getLogicHTML() {
    return `
        <div class="container" id="logic-list-container">
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('sudoku-workspace').style.display='flex'; window.initSudokuGrid && window.initSudokuGrid();">数独</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('akari-workspace').style.display='flex'; window.initGrid && window.initGrid();">Akari</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('aqre-workspace').style.display='flex'; window.initAqreGrid && window.initAqreGrid();">Aqre</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('aquapelago-workspace').style.display='flex'; window.initAquapelagoGrid && window.initAquapelagoGrid();">Aquapelago</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('aquarium-workspace').style.display='flex'; window.initAquariumGrid && window.initAquariumGrid();">Aquarium</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('balanceloop-workspace').style.display='flex'; window.initBalanceloopGrid && window.initBalanceloopGrid();">Balanceloop</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('battleship-workspace').style.display='flex'; window.initBattleshipGrid && window.initBattleshipGrid();">Battleship</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('binairo-workspace').style.display='flex'; window.initBinairoGrid && window.initBinairoGrid();">Binairo</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('castlewall-workspace').style.display='flex'; window.initCastlewallGrid && window.initCastlewallGrid();">Castlewall</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('cave-workspace').style.display='flex'; window.initCaveGrid && window.initCaveGrid();">Cave</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('chocobanana-workspace').style.display='flex'; window.initChocobananaGrid && window.initChocobananaGrid();">Chocobanana</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('chocona-workspace').style.display='flex'; window.initChoconaGrid && window.initChoconaGrid();">Chocona</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('countryroad-workspace').style.display='flex'; window.initCountryroadGrid && window.initCountryroadGrid();">Countryroad</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('doppelblock-workspace').style.display='flex'; window.initDoppelblockGrid && window.initDoppelblockGrid();">Doppelblock</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('easyas-workspace').style.display='flex'; window.initEasyasGrid && window.initEasyasGrid();">Easyas</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('fillomino-workspace').style.display='flex'; window.initFillominoGrid && window.initFillominoGrid();">Fillomino</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('gokigen-workspace').style.display='flex'; window.initGokigenGrid && window.initGokigenGrid();">Gokigen</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('haisu-workspace').style.display='flex'; window.initHaisuGrid && window.initHaisuGrid();">Haisu</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('haisuslow-workspace').style.display='flex'; window.initHaisuslowGrid && window.initHaisuslowGrid();">Haisuslow</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('hamle-workspace').style.display='flex'; window.initHamleGrid && window.initHamleGrid();">Hamle</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('hashi-workspace').style.display='flex'; window.initHashiGrid && window.initHashiGrid();">Hashi</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('heteromino-workspace').style.display='flex'; window.initHeterominoGrid && window.initHeterominoGrid();">Heteromino</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('heyawake-workspace').style.display='flex'; window.initHeyawakeGrid && window.initHeyawakeGrid();">Heyawake</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('hitori-workspace').style.display='flex'; window.initHitoriGrid && window.initHitoriGrid();">Hitori</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('hotaru-workspace').style.display='flex'; window.initHotaruGrid && window.initHotaruGrid();">Hotaru Beam</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('kakuro-workspace').style.display='flex'; window.initKakuroGrid && window.initKakuroGrid();">Kakuro</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('kuromasu-workspace').style.display='flex'; window.initKuromasuGrid && window.initKuromasuGrid();">Kuromasu</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('kurotto-workspace').style.display='flex'; window.initKurottoGrid && window.initKurottoGrid();">Kurotto</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('lits-workspace').style.display='flex'; window.initLITSGrid && window.initLITSGrid();">LITS</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('magnets-workspace').style.display='flex'; window.initMagnetsGrid && window.initMagnetsGrid();">Magnets</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('masyu-workspace').style.display='flex'; window.initMasyuGrid && window.initMasyuGrid();">Masyu</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('minesweeper-workspace').style.display='flex'; window.initMSGrid && window.initMSGrid();">Minesweeper</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('moonsun-workspace').style.display='flex'; window.initMSUGrid && window.initMSUGrid();">Moonsun</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('nagare-workspace').style.display='flex'; window.initNGGrid && window.initNGGrid();">Nagare</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('nanro-workspace').style.display='flex'; window.initNRGrid && window.initNRGrid();">Nanro</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('ncells-workspace').style.display='flex'; window.initNCGrid && window.initNCGrid();">Ncells</button>
            <button class="logic-btn" onclick="document.querySelectorAll('#logic-workspace-container > div').forEach(el => { if(el.id && el.id.endsWith('-workspace')) el.style.display='none'; }); document.getElementById('logic-list-container').style.display='none'; document.getElementById('logic-workspace-container').style.display='block'; document.getElementById('nonogram-workspace').style.display='flex'; window.initNOGrid && window.initNOGrid();">Nonogram</button>
            <a href="./logic/40_norinori.html" class="logic-btn">norinori</a>
            <a href="./logic/41_numberlink.html" class="logic-btn">numberlink</a>
            <a href="./logic/42_nuribou.html" class="logic-btn">nuribou</a>
            <a href="./logic/43_nurikabe.html" class="logic-btn">nurikabe</a>
            <a href="./logic/44_nurimisaki.html" class="logic-btn">nurimisaki</a>
            <a href="./logic/45_onsen.html" class="logic-btn">onsen</a>
            <a href="./logic/46_rippleeffect.html" class="logic-btn">rippleeffect</a>
            <a href="./logic/47_shakashaka.html" class="logic-btn">shakashaka</a>
            <a href="./logic/48_shikaku.html" class="logic-btn">shikaku</a>
            <a href="./logic/49_shimaguni.html" class="logic-btn">shimaguni</a>
            <a href="./logic/50_skyscrapers.html" class="logic-btn">skyscrapers</a>
            <a href="./logic/51_slitherlink.html" class="logic-btn">slitherlink</a>
            <a href="./logic/52_spiralgalaxies.html" class="logic-btn">spiralgalaxies</a>
            <a href="./logic/53_starbattle.html" class="logic-btn">starbattle</a>
            <a href="./logic/54_statuepark.html" class="logic-btn">statuepark</a>
            <a href="./logic/55_stostone.html" class="logic-btn">stostone</a>
            <a href="./logic/56_tapa.html" class="logic-btn">tapa</a>
            <a href="./logic/57_tatamibari.html" class="logic-btn">tatamibari</a>
            <a href="./logic/58_tents.html" class="logic-btn">tents</a>
            <a href="./logic/59_tll.html" class="logic-btn">tll</a>
            <a href="./logic/60_tren.html" class="logic-btn">tren</a>
            <a href="./logic/61_yajilin.html" class="logic-btn">yajilin</a>
            <a href="./logic/62_yajisankazusan.html" class="logic-btn">yajisankazusan</a>
            <a href="./logic/63_yinyang.html" class="logic-btn">yinyang</a>
        </div>
        
        <div id="logic-workspace-container" style="display: none; padding-top: 4rem; margin-top: 2rem;">
            ${(window.logicWorkspaceHTMLs || []).join('\n')}
        </div>
    </div>`;
}

function initLogicModule() {
    const container = document.getElementById('luojimiti');
    if (container) {
        container.innerHTML = getLogicHTML();
    }
}
